export const ALL_BOOKINGS_REQUEST="ALL_BOOKINGS_REQUEST";
export const ALL_BOOKINGS_SUCCESS="ALL_BOOKINGS_SUCCESS";
export const ALL_BOOKINGS_FAIL="ALL_BOOKINGS_FAIL";

export const GET_BOOKINGS_BY_USERID_REQUEST="GET_BOOKINGS_BY_USERID_REQUEST";
export const GET_BOOKINGS_BY_USERID_SUCCESS="GET_BOOKINGS_BY_USERID_SUCCESS";
export const GET_BOOKINGS_BY_USERID_FAIL="GET_BOOKINGS_BY_USERID_FAIL";

export const BOOKING_CREATE_REQUEST="BOOKING_CREATE_REQUEST";
export const BOOKING_CREATE_SUCCESS="BOOKING_CREATE_SUCCESS";
export const BOOKING_CREATE_RESET="BOOKING_CREATE_RESET";
export const BOOKING_CREATE_FAIL="BOOKING_CREATE_FAIL";
export const CLEAR_BOOKINGS_ERRORS="CLEAR_BOOKINGS_ERRORS";

export const BOOKING_DELETE_REQUEST="BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS="BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_RESET="BOOKING_DELETE_RESET";
export const BOOKING_DELETE_FAIL="BOOKING_DELETE_FAIL";

export const BOOKING_UPDATE_REQUEST="BOOKING_UPDATE_REQUEST";
export const BOOKING_UPDATE_SUCCESS="BOOKING_UPDATE_SUCCESS";
export const BOOKING_UPDATE_RESET="BOOKING_UPDATE_RESET";
export const BOOKING_UPDATE_FAIL="BOOKING_UPDATE_FAIL";

export const BOOKING_CANCEL_REQUEST="BOOKING_CANCEL_REQUEST";
export const BOOKING_CANCEL_SUCCESS="BOOKING_CANCEL_SUCCESS";
export const BOOKING_CANCEL_RESET="BOOKING_CANCEL_RESET";
export const BOOKING_CANCEL_FAIL="BOOKING_CANCEL_FAIL";