export const QUERY_DELETE_REQUEST="QUERY_DELETE_REQUEST";
export const QUERY_DELETE_SUCCESS="QUERY_DELETE_SUCCESS";
export const QUERY_DELETE_RESET="QUERY_DELETE_RESET";
export const QUERY_DELETE_FAIL="QUERY_DELETE_FAIL";

export const QUERY_UPDATE_REQUEST="QUERY_UPDATE_REQUEST";
export const QUERY_UPDATE_SUCCESS="QUERY_UPDATE_SUCCESS";
export const QUERY_UPDATE_RESET="QUERY_UPDATE_RESET";
export const QUERY_UPDATE_FAIL="QUERY_UPDATE_FAIL";
export const CLEAR_QUERY_ERRORS="CLEAR_QUERY_ERRORS";

export const GETALL_QUERY_REQUEST="GETALL_QUERY_REQUEST";
export const GETALL_QUERY_SUCCESS="GETALL_QUERY_SUCCESS";
export const GETALL_QUERY_FAIL="GETALL_QUERY_FAIL";