export const ALL_SERVICE_REQUEST="ALL_SERVICE_REQUEST";
export const ALL_SERVICE_SUCCESS="ALL_SERVICE_SUCCESS";
export const ALL_SERVICE_FAIL="ALL_SERVICE_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS";

export const SINGLE_SERVICE_REQUEST="SINGLE_SERVICE_REQUEST";
export const SINGLE_SERVICE_SUCCESS="SINGLE_SERVICE_SUCCESS";
export const SINGLE_SERVICE_FAIL="SINGLE_SERVICE_FAIL";

export const GET_SERVICE_REVIEW_REQUEST="GET_SERVICE_REVIEW_REQUEST";
export const GET_SERVICE_REVIEW_SUCCESS="GET_SERVICE_REVIEW_SUCCESS";
export const GET_SERVICE_REVIEW_FAIL="GET_SERVICE_REVIEW_FAIL";

export const REVIEW_DELETE_REQUEST="REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS="REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_RESET="REVIEW_DELETE_RESET";
export const REVIEW_DELETE_FAIL="REVIEW_DELETE_FAIL";

export const NEW_REVIEW_REQUEST="NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS="NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_RESET="NEW_REVIEW_RESET"
export const NEW_REVIEW_FAIL="NEW_REVIEW_FAIL"


export const ADMIN_ADD_SERVICE_REQUEST="ADMIN_ADD_SERVICE_REQUEST";
export const ADMIN_ADD_SERVICE_SUCCESS="ADMIN_ADD_SERVICE_SUCCESS";
export const ADMIN_ADD_SERVICE_RESET="ADMIN_ADD_SERVICE_RESET";
export const ADMIN_ADD_SERVICE_FAIL="ADMIN_ADD_SERVICE_FAIL";

export const ADMIN_UPDATE_SERVICE_REQUEST="ADMIN_UPDATE_SERVICE_REQUEST";
export const ADMIN_UPDATE_SERVICE_SUCCESS="ADMIN_UPDATE_SERVICE_SUCCESS";
export const ADMIN_UPDATE_SERVICE_RESET="ADMIN_UPDATE_SERVICE_RESET";
export const ADMIN_UPDATE_SERVICE_FAIL="ADMIN_UPDATE_SERVICE_FAIL";


export const ADMIN_DELETE_SERVICE_REQUEST="ADMIN_DELETE_SERVICE_REQUEST";
export const ADMIN_DELETE_SERVICE_SUCCESS="ADMIN_DELETE_SERVICE_SUCCESS";
export const ADMIN_DELETE_SERVICE_RESET="ADMIN_DELETE_SERVICE_RESET";
export const ADMIN_DELETE_SERVICE_FAIL="ADMIN_DELETE_SERVICE_FAIL";

