export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";

export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";

export const ADMIN_ALL_USER_REQUEST="ADMIN_ALL_USER_REQUEST";
export const ADMIN_ALL_USER_SUCCESS="ADMIN_ALL_USER_SUCCESS";
export const ADMIN_ALL_USER_FAIL="ADMIN_ALL_USER_FAIL";

export const ADMIN_USER_REQUEST="ADMIN_USER_REQUEST";
export const ADMIN_USER_SUCCESS="ADMIN_USER_SUCCESS";
export const ADMIN_USER_FAIL="ADMIN_USER_FAIL";

export const ADMIN_DELETE_USER_REQUEST="ADMIN_DELETE_USER_REQUEST";
export const ADMIN_DELETE_USER_SUCCESS="ADMIN_DELETE_USER_SUCCESS";
export const ADMIN_DELETE_USER_RESET="ADMIN_DELETE_USER_RESET";
export const ADMIN_DELETE_USER_FAIL="ADMIN_DELETE_USER_FAIL";

export const ADMIN_UPDATE_USER_REQUEST="ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS="ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_RESET="ADMIN_UPDATE_USER_RESET";
export const ADMIN_UPDATE_USER_FAIL="ADMIN_UPDATE_USER_FAIL";

export const CHANGE_USER_PASSWORD_REQUEST="CHANGE_USER_PASSWORD_REQUEST";
export const CHANGE_USER_PASSWORD_SUCCESS="CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_RESET="CHANGE_USER_PASSWORD_RESET";
export const CHANGE_USER_PASSWORD_FAIL="CHANGE_USER_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL";


export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const UPDATE_USERNAME_SUCCESS="UPDATE_USERNAME_SUCCESS";
export const UPDATE_USERNAME_FAIL="UPDATE_USERNAME_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";