export const NEW_WORKER_REQUEST="NEW_WORKER_REQUEST"
export const NEW_WORKER_SUCCESS="NEW_WORKER_SUCCESS"
export const NEW_WORKER_RESET="NEW_WORKER_RESET"
export const NEW_WORKER_FAIL="NEW_WORKER_FAIL"
export const CLEAR_WORKER_ERRORS="CLEAR_ERRORS";

export const ALL_WORKER_REQUEST="ALL_WORKER_REQUEST";
export const ALL_WORKER_SUCCESS="ALL_WORKER_SUCCESS";
export const ALL_WORKER_FAIL="ALL_WORKER_FAIL";

export const  DELETE_WORKER_REQUEST=" DELETE_WORKER_REQUEST";
export const  DELETE_WORKER_SUCCESS=" DELETE_WORKER_SUCCESS";
export const  DELETE_WORKER_RESET=" DELETE_WORKER_RESET";
export const  DELETE_WORKER_FAIL=" DELETE_WORKER_FAIL";

export const  UPDATE_WORKER_REQUEST=" UPDATE_WORKER_REQUEST";
export const  UPDATE_WORKER_SUCCESS=" UPDATE_WORKER_SUCCESS";
export const  UPDATE_WORKER_RESET=" UPDATE_WORKER_RESET";
export const  UPDATE_WORKER_FAIL=" UPDATE_WORKER_FAIL";